name: Bug report
about: Report a bug in GodSVG
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe your issue
      placeholder: Description text
      description: |
        Give a clear and concise description of what the bug is and what the expected behavior is. 
        For non-trivial issues, provide reproduction steps and screenshots or video if relevant.
