name: Bug report
description: Report a bug in GodSVG
title: "Title"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    placeholder: |
      Give a clear and concise description of what the bug is and what the expected behavior is. 
      For non-trivial issues, provide reproduction steps and screenshots or video if relevant.
