name: Feature request
description: Suggest a new feature for GodSVG
title: "Title"
labels: [proposal]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Give a clear and concise description of what the bug is and what the expected behavior is. 
        For non-trivial issues, provide reproduction steps and screenshots or video if relevant.
